service: buttonbox-iot-event-processor

frameworkVersion: ">=1.5.0 <2.0.0"

provider:
  name: aws
  region: us-west-2
  runtime: nodejs8.10
  profile: button-box-serverless
  iamRoleStatements:
    - Effect: Allow
      Action:
        - iot:UpdateThingShadow
        - iot:GetThingShadow
        - iot:ListThingGroupsForThing
        - iot:ListThingsInThingGroup
      Resource: "*"

functions:
  change-handler:
    memorySize: 256
    handler: handler.handle
    events:
      - iot:
          sql: "SELECT *, clientid() as clientId, newuuid() as randomUUID FROM '$aws/things/esp32_14958C/shadow/update'"
