service: buttonbox-iot-event-processor

frameworkVersion: ">=1.5.0 <2.0.0"

provider:
  name: aws
  region: us-west-2
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - iot:UpdateThingShadow
        - iot:GetThingShadow
      Resource: "*"

functions:
  change-handler:
    memorySize: 256
    handler: handler.handle
    events:
      - iot:
          sql: "SELECT * FROM '$aws/things/esp32_14958C/shadow/update'"
# resources:
#   Resources:
#     MyPolicy:
#       Type: AWS::IoT::Policy
#       Properties:
#         PolicyDocument:
#           Version: "2012-10-17"
#           Statement:
#             - Effect: "Allow"
#               Action:
#                 - "iot:UpdateThingShadow"
#                 - "iot:GetThingShadow"
#               Resource:
#                 - "*"
